{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "ContactsAPI",
    "description" : "Lesson4",
    "version" : "1.1.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/FAN19005/Contacts/1.1.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : { },
  "components" : { }
}