{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Contacts",
    "description" : "lesson4",
    "version" : "1.0.1"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/FAN19005/ContactsAPI/1.0.1",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : { },
  "components" : { }
}